@startuml
'https://plantuml.com/class-diagram

interface IQLSV{
void add(SinhVienCNTT sv)
void print()
}
class QLSV
class SinhVienCNTT{
-String ten,queQuan
-int tuoi
}
class SinhVienCNTT_CLC
SinhVienCNTT <|- SinhVienCNTT_CLC
IQLSV <|.. QLSV
QLSV *--> "list" SinhVienCNTT

@enduml